on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  pull_and_deploy:
    name: pull_and_deploy
    runs-on: ubuntu-latest
    steps:
      - name: setup ssh
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.PORT }} -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
      - name: connect, pull and deploy
        run: |
          ssh -p ${{ secrets.PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} <<'ENDSSH'
          cd ${{ secrets.SSH_WORKDIR }}
          git pull
          cd iam
          docker compose -f docker-compose.prod.yaml up -d
          cd ../auth
          docker compose -f docker-compose.prod.yaml up -d --build
          ENDSSH
      - name: cleanup
        run: rm -rf ~/.ssh
